# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['setting.pyw'],
    pathex=['.', 'src'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'tools.ambient_audio',
        'tools.frame_extractor',
        'tools.lasso_manager',
        'tools.process_manager',
        'ui.panels',
        'ui.widgets',
        'ui.help',
        'ui.theme',
        'ui.theme_dark',
        'ui.dialog',
        'ui.tray_icon',
        'ui.lasso_window',
        'session',
        'sprite_loader',
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtSvg',
        'PySide6.QtNetwork',
        'pygame',
        'pygame.mixer',
        'pygame.display',
        'pygame.event',
        'pygame.image',
        'pygame.time',
        'win32gui',
        'win32con',
        'win32api',
        'win32process',
        'pywintypes',
        'winreg',
        'psutil',
        'cv2',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'tkinter',
        'tkinter.messagebox',
        'ast',
        'threading',
        'json',
        'configparser',
        'subprocess',
        'webbrowser',
        'shutil',
        'random',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'keyboard',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Spryta',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icons/icon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Spryta',
)
